// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bNJjNc2NbC4jfBdycy75o8
// Component: iXxSJX956e4d
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Logo from "../../Logo"; // plasmic-import: dbGVEXIYhu_f/component
import Button from "../../Button"; // plasmic-import: 9tG1OyZAVIis/component

import { useScreenVariants as useScreenVariantsxs8LqfxZhwLy } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: XS8lqfxZhwLY/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: bNJjNc2NbC4jfBdycy75o8/projectcss
import * as sty from "./PlasmicFooterSection.module.css"; // plasmic-import: iXxSJX956e4d/css

import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: xwxygpKk6efH/icon
import GithubIcon from "./icons/PlasmicIcon__Github"; // plasmic-import: GenxYUKBTlHD/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin"; // plasmic-import: G01pIb6GIpgD/icon
import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: MwxVTyBYf-O_/icon

export type PlasmicFooterSection__VariantMembers = {};

export type PlasmicFooterSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterSection__VariantsArgs;
export const PlasmicFooterSection__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterSection__ArgsType = {};
type ArgPropType = keyof PlasmicFooterSection__ArgsType;
export const PlasmicFooterSection__ArgProps = new Array<ArgPropType>();

export type PlasmicFooterSection__OverridesType = {
  root?: p.Flex<"div">;
  logo?: p.Flex<typeof Logo>;
};

export interface DefaultFooterSectionProps {
  className?: string;
}

function PlasmicFooterSection__RenderFunc(props: {
  variants: PlasmicFooterSection__VariantsArgs;
  args: PlasmicFooterSection__ArgsType;
  overrides: PlasmicFooterSection__OverridesType;
  dataFetches?: PlasmicFooterSection__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxs8LqfxZhwLy()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___8RjJ4)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__ezOj3)}
        >
          <Logo
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            _50Opaque={"_50Opaque" as const}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__b2XVw)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hC0E
              )}
            >
              {"Connect with us"}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__eoeYd)}
            >
              <TwitterIcon
                className={classNames(projectcss.all, sty.svg__f81D6)}
                role={"img"}
              />

              <GithubIcon
                className={classNames(projectcss.all, sty.svg__eZhSm)}
                role={"img"}
              />

              <LinkedinIcon
                className={classNames(projectcss.all, sty.svg___3JwXt)}
                role={"img"}
              />
            </p.Stack>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__ej5Y)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___1RCgQ
            )}
          >
            {"Product"}
          </div>

          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__tGoa1)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yv1R8
                )}
              >
                {"Pricing"}
              </div>
            </Button>
          ) : null}

          <Button
            className={classNames("__wab_instance", sty.button__gFwLl)}
            color={"navLink" as const}
            flat={"flat" as const}
            link={"/dashboard" as const}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ztX8Y
              )}
            >
              {"Log in"}
            </div>
          </Button>

          <Button
            className={classNames("__wab_instance", sty.button__vvfWx)}
            color={"navLink" as const}
            flat={"flat" as const}
            link={"/docs" as const}
          >
            {"Documentation"}
          </Button>

          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__s88Cu)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xO6Tw
                )}
              >
                {"Integrations"}
              </div>
            </Button>
          ) : null}
          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__vpTnX)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jmSjY
                )}
              >
                {"Insights"}
              </div>
            </Button>
          ) : null}
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__adWjy)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__p4Z5R
            )}
          >
            {"Company"}
          </div>

          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__fO03)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              {"About"}
            </Button>
          ) : null}
          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__nViHn)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              {"Contact us"}
            </Button>
          ) : null}
          {true ? (
            <Button
              className={classNames("__wab_instance", sty.button__rx9Bh)}
              color={"navLink" as const}
              flat={"flat" as const}
            >
              {"Careers"}
            </Button>
          ) : null}

          <Button
            className={classNames("__wab_instance", sty.button___4XmSe)}
            color={"navLink" as const}
            flat={"flat" as const}
            link={"/blog" as const}
          >
            {"Blog"}
          </Button>

          <Button
            className={classNames("__wab_instance", sty.button___1Gtq3)}
            color={"navLink" as const}
            flat={"flat" as const}
            link={"https://fathym.com/privacy-policy/" as const}
          >
            {"Privacy"}
          </Button>

          <Button
            className={classNames("__wab_instance", sty.button__n8JQ)}
            color={"navLink" as const}
            flat={"flat" as const}
            link={"https://fathym.com/terms-of-services/" as const}
          >
            {"Terms"}
          </Button>
        </p.Stack>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "logo"],
  logo: ["logo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  logo: typeof Logo;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterSection__VariantsArgs;
    args?: PlasmicFooterSection__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFooterSection__Fetches;
  } & Omit<PlasmicFooterSection__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooterSection__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooterSection__ArgProps,
      internalVariantPropNames: PlasmicFooterSection__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFooterSection__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterSection";
  } else {
    func.displayName = `PlasmicFooterSection.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterSection = Object.assign(
  // Top-level PlasmicFooterSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logo: makeNodeComponent("logo"),

    // Metadata about props expected for PlasmicFooterSection
    internalVariantProps: PlasmicFooterSection__VariantProps,
    internalArgProps: PlasmicFooterSection__ArgProps
  }
);

export default PlasmicFooterSection;
/* prettier-ignore-end */
